#Expyriment 1.0.0 (Python 3.10.4), .xpe-file, coding: cp1252
#date: Sun Sep 21 2025 16:56:53
#sha1: 847ce8
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='PORT-HP', release='10', version='10.0.19045', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
646,stderr,received,'Traceback (most recent call last):\n  File "C:\\Users\\Abel COIFFARD\\Desktop\\Cours\\M1\\S1\\Exp_approach\\cogsup-prog\\Assignments\\Week-2\\Exercises\\labeled_shapes.py", line 14, in <module>\n    triangle = stimuli.Shape(position = (125,0), colour = (0, 0, 255), vertex_list = {(43*math.cos(90), 43*math.sin(90)),(43*math.cos(210), 43*math.sin(210)),(43*math.cos(340), 43*math.sin(340))})\n  File "C:\\Users\\Abel COIFFARD\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\expyriment\\stimuli\\_shape.py", line 164, in __init__\n    self.add_vertices(vertex_list=vertex_list)\n  File "C:\\Users\\Abel COIFFARD\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\expyriment\\stimuli\\_shape.py", line 414, in add_vertices\n    raise TypeError(type_error_message)\nTypeError: The method add_vertices requires a list of tuples as argument.'
