#Expyriment 1.0.0 (Python 3.10.4), .xpe-file, coding: cp1252
#date: Fri Sep 26 2025 06:54:54
#sha1: 73ee28
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='PORT-HP', release='10', version='10.0.19045', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
462,Stimulus,presented,3
463,stderr,received,'Traceback (most recent call last):\n  File "C:\\Users\\Abel COIFFARD\\Desktop\\Cours\\M1\\S1\\Exp_approach\\cogsup-prog\\Assignments\\Week-3\\Exercises\\kanizsa-square.py", line 23, in <module>\n    circles[1].present(clear=False, update =False)\nIndexError: list index out of range'
